### ISSUE TITLE
I have problem with permission denied

### ISSUE THREAD

**Issue by kazekim** [tinrab/go-mongo-docker-example#3]
I got this message while I try running docker-compose up

package github.com/pilu/fresh: mkdir /go/src/github.com/pilu/: permission denied

It was caused by user api doesn't have permission to mkdir in /go/src

Have you ever found this problem?

Note : I have changed volume value of api in your docker-compose.yaml from your code to something like this
volumes:
      - './api:/go/src/github.com/kazekim/devcurateapi-go/api'

**Comment by tinrab** [comment]
I never encountered this, no. The problem seems to be with user permissions and docker. There's probably better ways to achieve this. "docker image security" google search could suffice.

**Comment by kazekim** [comment]
Thanks I will try to find the way first and update again. It should be useful.
